version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: weirdlady_site
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

